version: "3"
services:
  blog-node-app:
    container_name: blog-node-app
    build: 
      context: .
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - NODE_ENV=PRODUCTION  
      - UPLOAD_DIR=${UPLOAD_DIR}
    command: npm run prod  

  blog-redis:
    container_name: blog-redis
    image: "redis:latest"
    ports:
      - "63079:6379"
    expose:
      - 6379  