version: "3"
services:
  blog-node-app:
    container_name: blog-node-app
    build: 
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development  
    command: npm run dev  
    depends_on:
      - blog-db8
      - blog-redis

  blog-redis:
    container_name: blog-redis
    image: "redis:latest"
    ports:
      - "63079:6379"
    expose:
      - 6379

  blog-db8:
    container_name: blog-db8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - blog-data8:/var/lib/mysql
      - ./docker/mysql/:/docker-entrypoint-initdb.d
    ports:
      - "33069:3306"
    expose:
      - 3306

volumes:
  blog-data8: